name: Generate PDF
on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 'latest'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf

      - name: Convert Markdown to HTML
        run: pandoc README.md -o output.html --css=styles.css

      - name: Convert HTML to PDF
        run: wkhtmltopdf --enable-local-file-access output.html Andrew-Wilkes-Resume.pdf
        
      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update resume PDF [skip ci]"
          file_pattern: Andrew-Wilkes-Resume.pdf
