name: Generate PDF
on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 'latest'

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex

      - name: Generate PDF
        run: |
          pandoc README.md -o Andrew-Wilkes-Resume.pdf --pdf-engine=xelatex -V geometry:margin=1in

      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update resume PDF [skip ci]"
          file_pattern: Andrew-Wilkes-Resume.pdf
